'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {useApp,useDebounce,useQuery,usePage} from '@/lib/gateway';
import {categories,sourceNames,type Row} from '@/lib/brand';
import {SearchBox,Pager,Loading,Failure,Button,Choice,Field} from './ui';
/** Selection persists across pages; ids are resolved and authorized again by SQL. */
export function TargetPicker({kind='both',value,onChange,prefixed=false}:{kind?:'both'|'members'|'groups';value:string[];onChange:(v:string[])=>void;prefixed?:boolean}){
 const{api,run}=useApp();const[tab,setTab]=useState(kind==='groups'?'groups':'members'),[search,setSearch]=useState(''),[area,setArea]=useState(''),[category,setCategory]=useState('all'),[source,setSource]=useState('all'),[page,setPage]=useState(0),[busy,setBusy]=useState(false);
 const args={search:useDebounce(search),area:useDebounce(area),category,source,status:'approved'};const{rows,total,loading,error}=useQuery(tab,{...args,page});const key=(r:Row)=>(prefixed?(tab==='groups'?'g:':'u:'):'')+r.id;
 const all=()=>{setBusy(true);void run(async()=>{const picked:string[]=[];let page=0,count=0;do{const batch=await api.query(tab,{...args,page,limit:100});picked.push(...batch.rows.map(key));count=batch.total;page++;if(!batch.rows.length)break}while(picked.length<count);onChange(Array.from(new Set([...value,...picked])))},'検索結果を選択しました').finally(()=>setBusy(false))};
 return <div className="stack">{kind==='both'&&<Choice label="対象を探す" value={tab} onChange={v=>{setTab(v);setPage(0)}} options={[["members","メンバー"],["groups","グループ"]]}/>}<SearchBox value={search} onChange={v=>{setSearch(v);setPage(0)}} placeholder={tab==='groups'?'グループ名で検索':'表示名で検索'}/>{tab==='members'&&<details><summary>地域・職種・登録経路で絞り込む</summary><Field label="地域" value={area} onChange={v=>{setArea(v);setPage(0)}}/><Choice label="職種" value={category} onChange={v=>{setCategory(v);setPage(0)}} options={[["all","すべて"],...categories]}/><Choice label="登録経路" value={source} onChange={v=>{setSource(v);setPage(0)}} options={[["all","すべて"],...Object.entries(sourceNames)]}/></details>}{loading?<Loading/>:error?<Failure message={error}/>:<div className="target-list">{rows.map(r=><label className="check" key={r.id}><Checkbox checked={value.includes(key(r))} onCheckedChange={v=>onChange(v?Array.from(new Set([...value,key(r)])):value.filter(id=>id!==key(r)))}/>{r.display_name||r.name} {r.area}</label>)}</div>}<Pager page={page} total={total} onChange={setPage}/><div className="row wrap"><Button secondary disabled={busy||!total} onClick={all}>{busy?'選択中…':`検索結果${total}件を選択`}</Button><Button secondary disabled={!value.length} onClick={()=>onChange([])}>選択を解除</Button><small>選択済み {value.length}件</small></div></div>
}
export function RecordPicker({table,column='name',value,onChange,label,empty='選択してください'}:{table:string;column?:string;value:string;onChange:(id:string)=>void;label:string;empty?:string}){
 const[search,setSearch]=useState('');const{rows,total,page,setPage,loading,error}=usePage(table,{},useDebounce(search),column);return <div className="stack"><SearchBox value={search} onChange={setSearch} placeholder={label+'を検索'}/>{loading?<Loading/>:error?<Failure message={error}/>:<Choice label={label} value={value} onChange={onChange} options={[["none",empty],...(!rows.some(r=>r.id===value)&&value&&value!=='none'?[[value,'選択済み'] as [string,string]]:[]),...rows.map(r=>[r.id,r[column]] as [string,string])]}/>}<Pager page={page} total={total} onChange={setPage}/></div>
}
