'use client';import {useEffect,useState,type ReactNode} from 'react';import {ArrowLeft,Inbox,Search,AlertCircle} from 'lucide-react';import {brand,labels} from '@/lib/brand';import {useApp} from '@/lib/gateway';import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';import {Skeleton} from '@/components/ui/skeleton';
export function Logo({small=false}:{small?:boolean}){return <span className={'logo '+(small?'small':'')}><svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M12 12v22c0 14 24 14 24 0V12" stroke="currentColor" strokeWidth="8" strokeLinecap="round"/><path d="M28 52V30c0-14 24-14 24 0v22" stroke={brand.aqua} strokeWidth="8" strokeLinecap="round"/></svg><span>{brand.name}</span></span>}
export function Button({children,onClick,type='button',secondary=false,disabled=false}:{children:ReactNode;onClick?:()=>void;type?:'button'|'submit';secondary?:boolean;disabled?:boolean}){return <button type={type} className={'btn '+(secondary?'secondary':'')} onClick={onClick} disabled={disabled}>{children}</button>}
export function Field({label,value,onChange,type='text',multiline=false,required=false,placeholder=''}:{label:string;value?:string|number;onChange:(v:string)=>void;type?:string;multiline?:boolean;required?:boolean;placeholder?:string}){return <label className="field"><span>{label}{required&&<em>必須</em>}</span>{multiline?<textarea value={value??''} onChange={e=>onChange(e.target.value)} required={required} placeholder={placeholder} maxLength={5000}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} required={required} placeholder={placeholder}/>}</label>}
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:(string|[string,string])[]}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const[v,t]=typeof o==='string'?[o,o]:o;return <SelectItem key={v} value={v}>{t}</SelectItem>})}</SelectContent></Select></div>}
export function Tag({children,tone='aqua'}:{children:ReactNode;tone?:string}){return <span className={'tag '+tone}>{children}</span>}export function Status({value}:{value:string}){return <Tag tone={['pending','draft','queued','scheduled'].includes(value)?'amber':['failed','banned','rejected','suspended'].includes(value)?'red':'aqua'}>{labels[value]||value}</Tag>}
export function Avatar({name,url}:{name:string;url?:string}){const{api}=useApp();const[src,setSrc]=useState('');useEffect(()=>{let live=true;if(!url){setSrc('');return}if(/^https:\/\/|^data:image\//.test(url))setSrc(url);else api.client?.storage.from('avatars').createSignedUrl(url,300).then(({data})=>{if(live)setSrc(data?.signedUrl||'')});return()=>{live=false}},[url,api]);return <span className="avatar">{name.slice(0,1)}{src&&<img src={src} alt="" onError={()=>setSrc('')}/>}</span>}
export function Heading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</header>}
export function SearchBox({value,onChange,placeholder='検索'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="search"><Search size={18}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><Inbox size={32}/><h3>{title}</h3>{children&&<p>{children}</p>}</div>}
export function Loading(){const[slow,setSlow]=useState(false);useEffect(()=>{const timer=setTimeout(()=>setSlow(true),12000);return()=>clearTimeout(timer)},[]);if(slow)return <Failure message="読み込みに時間がかかっています。通信状態を確認して、再読み込みしてください。"/>;return <div role="status" aria-label="読み込み中" className="stack"><Skeleton className="h-16 w-full"/><Skeleton className="h-40 w-full"/><Skeleton className="h-40 w-full"/></div>}
export function Failure({message}:{message:string}){return <div className="notice error" role="alert"><AlertCircle/><div><strong>表示できませんでした</strong><p>{message}</p><button onClick={()=>location.reload()}>再読み込み</button></div></div>}
export function Modal({trigger,title,children,description}:{trigger:ReactNode;title:string;children:ReactNode;description?:string}){return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent className="mu-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'内容を確認して保存してください。'}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function Back({href}:{href:string}){return <a className="back" href={href}><ArrowLeft size={16}/>戻る</a>}
export function Pager({page,total,onChange,size=25}:{page:number;total:number;onChange:(page:number)=>void;size?:number}){return <nav className="row wrap" aria-label="一覧のページ" style={{marginTop:24,justifyContent:'space-between'}}><Button secondary disabled={page===0} onClick={()=>onChange(page-1)}>前へ</Button><span className="muted" aria-live="polite">{total?`${page*size+1}–${Math.min((page+1)*size,total)} / ${total}件`:'0件'}</span><Button secondary disabled={(page+1)*size>=total} onClick={()=>onChange(page+1)}>次へ</Button></nav>}
